
name: 'greenery'
version: '1.0.0'
config-version: 2


profile: 'greenery'    # profile to use for this project

# file locations
model-paths: ["models"]   # folder with the models
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  greenery:
    # post-hook grants access to this role to each model AFTER EACH model that runs
    +post-hook:
          - "{{ grant(role='reporting') }}"

    # tell dbt to build all models in the example/ directory as tables
    # can be overridden in the individual model files using the `{{ config(...) }}` macro
    # Config indicated by + and applies to all files under models/example/
    # example:
    #   +materialized: view
